import { Exam, Question, CurrentArticle, LeaderboardEntry } from '@/types';

export const EXAMS: Exam[] = [
    {
        id: 'upsc-cse',
        name: 'UPSC CSE',
        category: 'upsc',
        description: 'Civil Services Examination — Prelims GS Paper I',
        languages: ['en'],
        negative_marking: 0.33,
        subjects: ['Ancient History', 'Art and Culture', 'Modern History', 'Polity', 'Economics', 'Geography', 'Environment', 'IR and Current Affairs', 'General Awareness'],
        icon: '🏛️',
        color: '#082C54',
    },
    {
        id: 'upsc-capf',
        name: 'UPSC CAPF',
        category: 'upsc',
        description: 'Central Armed Police Forces — General Ability & Intelligence',
        languages: ['en'],
        negative_marking: 0.33,
        subjects: ['General Knowledge', 'Current Affairs', 'Reasoning', 'English'],
        icon: '🎖️',
        color: '#0D5D56',
    },
    {
        id: 'upsc-cds',
        name: 'UPSC CDS',
        category: 'upsc',
        description: 'Combined Defence Services — General Knowledge',
        languages: ['en'],
        negative_marking: 0.33,
        subjects: ['History', 'Geography', 'Polity', 'Science', 'Defence'],
        icon: '⚔️',
        color: '#B83E11',
    },
    {
        id: 'rbi-grade-b',
        name: 'RBI Grade B',
        category: 'upsc',
        description: 'Reserve Bank of India — Phase I General Awareness',
        languages: ['en'],
        negative_marking: 0.25,
        subjects: ['Economy', 'Banking', 'Current Affairs', 'Polity'],
        icon: '🏦',
        color: '#E67E22',
    },
    {
        id: 'kpsc-kas',
        name: 'KPSC KAS',
        name_kn: 'ಕೆಪಿಎಸ್‌ಸಿ ಕೆಎಎಸ್',
        category: 'karnataka',
        description: 'Karnataka Administrative Service — Prelims',
        description_kn: 'ಕರ್ನಾಟಕ ಆಡಳಿತ ಸೇವೆ — ಪ್ರಾಥಮಿಕ ಪರೀಕ್ಷೆ',
        languages: ['en', 'kn'],
        negative_marking: 0.25,
        subjects: ['Karnataka History', 'Indian Polity', 'Economy', 'Kannada', 'Science'],
        icon: '🅺',
        color: '#B83E11',
    },
    {
        id: 'kpsc-psi',
        name: 'KPSC PSI',
        name_kn: 'ಕೆಪಿಎಸ್‌ಸಿ ಪಿಎಸ್‌ಐ',
        category: 'karnataka',
        description: 'Police Sub-Inspector Recruitment',
        description_kn: 'ಪೊಲೀಸ್ ಉಪ-ನಿರೀಕ್ಷಕ ನೇಮಕಾತಿ',
        languages: ['en', 'kn'],
        negative_marking: 0,
        subjects: ['General Knowledge', 'Kannada', 'Reasoning', 'Law'],
        icon: '👮',
        color: '#0D5D56',
    },
    {
        id: 'kpsc-pc',
        name: 'KPSC Police Constable',
        name_kn: 'ಕೆಪಿಎಸ್‌ಸಿ ಪೊಲೀಸ್ ಕಾನ್ಸ್ಟೇಬಲ್',
        category: 'karnataka',
        description: 'Police Constable Recruitment',
        description_kn: 'ಪೊಲೀಸ್ ಕಾನ್ಸ್ಟೇಬಲ್ ನೇಮಕಾತಿ',
        languages: ['en', 'kn'],
        negative_marking: 0,
        subjects: ['General Knowledge', 'Kannada', 'Reasoning'],
        icon: '🚔',
        color: '#082C54',
    },
    {
        id: 'kea-group-c',
        name: 'KEA Group C & D',
        name_kn: 'ಕೆಇಎ ಗ್ರೂಪ್ ಸಿ ಮತ್ತು ಡಿ',
        category: 'karnataka',
        description: 'Karnataka Examinations Authority — Group C & D',
        description_kn: 'ಕರ್ನಾಟಕ ಪರೀಕ್ಷಾ ಪ್ರಾಧಿಕಾರ — ಗ್ರೂಪ್ ಸಿ ಮತ್ತು ಡಿ',
        languages: ['en', 'kn'],
        negative_marking: 0,
        subjects: ['General Knowledge', 'Kannada', 'Maths', 'Reasoning'],
        icon: '📋',
        color: '#E67E22',
    },
];

export const QUESTIONS: Question[] = [
    // UPSC CSE — History
    {
        id: 'q1',
        exam_id: 'upsc-cse',
        subject: 'History',
        difficulty: 'easy',
        text: 'Who was the founder of the Maurya Empire?',
        options: [
            { id: 'a', text: 'Ashoka' },
            { id: 'b', text: 'Chandragupta Maurya' },
            { id: 'c', text: 'Bindusara' },
            { id: 'd', text: 'Bimbisara' },
        ],
        correct: 'b',
        explanation: 'Chandragupta Maurya founded the Maurya Empire around 322 BCE with the help of Chanakya. He overthrew the Nanda dynasty.',
    },
    {
        id: 'q2',
        exam_id: 'upsc-cse',
        subject: 'History',
        difficulty: 'medium',
        text: 'The Battle of Plassey (1757) was fought between the British East India Company and whom?',
        options: [
            { id: 'a', text: 'Tipu Sultan' },
            { id: 'b', text: 'Siraj ud-Daulah, Nawab of Bengal' },
            { id: 'c', text: 'Hyder Ali' },
            { id: 'd', text: 'The Maratha Confederacy' },
        ],
        correct: 'b',
        explanation: 'The Battle of Plassey was fought on June 23, 1757 between the British East India Company and Siraj ud-Daulah, the Nawab of Bengal. It marked the beginning of British rule in India.',
    },
    {
        id: 'q3',
        exam_id: 'upsc-cse',
        subject: 'History',
        difficulty: 'hard',
        text: 'Which of the following correctly describes the "Subsidiary Alliance" introduced by Lord Wellesley?',
        options: [
            { id: 'a', text: 'Indian states had to accept British troops and pay for their maintenance' },
            { id: 'b', text: 'Indian states were annexed directly into British territory' },
            { id: 'c', text: 'Indian kings had to pay a fixed tribute to the British every year' },
            { id: 'd', text: 'Indian states had to supply soldiers to the British army' },
        ],
        correct: 'a',
        explanation: 'The Subsidiary Alliance required Indian rulers to accept British troops for their protection, dismiss their own armies, and pay for the maintenance of the British forces. Failure to pay led to annexation of territory.',
    },
    // UPSC CSE — Polity
    {
        id: 'q4',
        exam_id: 'upsc-cse',
        subject: 'Polity',
        difficulty: 'easy',
        text: 'Which article of the Indian Constitution abolishes untouchability?',
        options: [
            { id: 'a', text: 'Article 14' },
            { id: 'b', text: 'Article 17' },
            { id: 'c', text: 'Article 21' },
            { id: 'd', text: 'Article 32' },
        ],
        correct: 'b',
        explanation: 'Article 17 of the Indian Constitution abolishes untouchability and forbids its practice in any form. Enforcement of any disability arising out of untouchability is an offence punishable by law.',
    },
    {
        id: 'q5',
        exam_id: 'upsc-cse',
        subject: 'Polity',
        difficulty: 'medium',
        text: 'The concept of "Basic Structure" of the Constitution was propounded in which landmark case?',
        options: [
            { id: 'a', text: 'Golaknath v. State of Punjab' },
            { id: 'b', text: 'Maneka Gandhi v. Union of India' },
            { id: 'c', text: 'Kesavananda Bharati v. State of Kerala' },
            { id: 'd', text: 'Minerva Mills v. Union of India' },
        ],
        correct: 'c',
        explanation: 'The Basic Structure doctrine was propounded in Kesavananda Bharati v. State of Kerala (1973). The Supreme Court held that while Parliament can amend the Constitution, it cannot destroy its basic structure.',
    },
    {
        id: 'q6',
        exam_id: 'upsc-cse',
        subject: 'Polity',
        difficulty: 'hard',
        text: 'Under which schedule of the Indian Constitution are the Anti-Defection provisions contained?',
        options: [
            { id: 'a', text: 'Eighth Schedule' },
            { id: 'b', text: 'Ninth Schedule' },
            { id: 'c', text: 'Tenth Schedule' },
            { id: 'd', text: 'Eleventh Schedule' },
        ],
        correct: 'c',
        explanation: 'The Tenth Schedule, added by the 52nd Amendment (1985), provides for disqualification of members on grounds of defection. A member is disqualified if they voluntarily give up membership of their party.',
    },
    // UPSC CSE — Economy
    {
        id: 'q7',
        exam_id: 'upsc-cse',
        subject: 'Economy',
        difficulty: 'easy',
        text: 'Which institution publishes the "World Economic Outlook" report?',
        options: [
            { id: 'a', text: 'World Bank' },
            { id: 'b', text: 'International Monetary Fund' },
            { id: 'c', text: 'WTO' },
            { id: 'd', text: 'UNCTAD' },
        ],
        correct: 'b',
        explanation: 'The International Monetary Fund (IMF) publishes the World Economic Outlook (WEO) twice a year, providing analysis and projections for the global economy.',
    },
    {
        id: 'q8',
        exam_id: 'upsc-cse',
        subject: 'Economy',
        difficulty: 'medium',
        text: 'What is the primary objective of the Monetary Policy Committee (MPC) in India?',
        options: [
            { id: 'a', text: 'Regulate stock market indices' },
            { id: 'b', text: 'Maintain price stability with focus on growth' },
            { id: 'c', text: 'Control government fiscal deficit' },
            { id: 'd', text: 'Manage foreign exchange reserves' },
        ],
        correct: 'b',
        explanation: 'The MPC of the RBI is mandated to maintain price stability (CPI inflation target of 4% ±2%) while keeping in mind the objective of economic growth.',
    },
    // UPSC CSE — Science
    {
        id: 'q9',
        exam_id: 'upsc-cse',
        subject: 'Science',
        difficulty: 'easy',
        text: 'Which gas is primarily responsible for the greenhouse effect?',
        options: [
            { id: 'a', text: 'Oxygen' },
            { id: 'b', text: 'Nitrogen' },
            { id: 'c', text: 'Carbon Dioxide' },
            { id: 'd', text: 'Hydrogen' },
        ],
        correct: 'c',
        explanation: 'Carbon dioxide (CO2) is the primary greenhouse gas emitted through human activities such as burning of fossil fuels and deforestation. It traps heat in the atmosphere causing global warming.',
    },
    {
        id: 'q10',
        exam_id: 'upsc-cse',
        subject: 'Environment',
        difficulty: 'medium',
        text: 'The "Ramsar Convention" is associated with which type of ecosystem?',
        options: [
            { id: 'a', text: 'Forests' },
            { id: 'b', text: 'Wetlands' },
            { id: 'c', text: 'Coral Reefs' },
            { id: 'd', text: 'Deserts' },
        ],
        correct: 'b',
        explanation: 'The Ramsar Convention is an international treaty for the conservation and sustainable use of wetlands. It was adopted in 1971 in Ramsar, Iran. India has the highest number of Ramsar sites in South Asia.',
    },
    // KPSC KAS — Karnataka History
    {
        id: 'q11',
        exam_id: 'kpsc-kas',
        subject: 'Karnataka History',
        difficulty: 'easy',
        text: 'Which dynasty built the famous Brihadeeshwara Temple at Thanjavur?',
        text_kn: 'ತಂಜಾವೂರಿನ ಪ್ರಸಿದ್ಧ ಬೃಹದೀಶ್ವರ ದೇವಾಲಯವನ್ನು ಯಾವ ರಾಜವಂಶ ನಿರ್ಮಿಸಿತು?',
        options: [
            { id: 'a', text: 'Chalukya', text_kn: 'ಚಾಲುಕ್ಯ' },
            { id: 'b', text: 'Rashtrakuta', text_kn: 'ರಾಷ್ಟ್ರಕೂಟ' },
            { id: 'c', text: 'Chola', text_kn: 'ಚೋಳ' },
            { id: 'd', text: 'Hoysala', text_kn: 'ಹೊಯ್ಸಳ' },
        ],
        correct: 'c',
        explanation: 'The Brihadeeshwara Temple at Thanjavur was built by Raja Raja Chola I around 1010 CE. It is a UNESCO World Heritage Site.',
        explanation_kn: 'ತಂಜಾವೂರಿನ ಬೃಹದೀಶ್ವರ ದೇವಾಲಯವನ್ನು ರಾಜ ರಾಜ ಚೋಳ-I ಅವರು ಸುಮಾರು 1010 CE ಯಲ್ಲಿ ನಿರ್ಮಿಸಿದರು.',
    },
    {
        id: 'q12',
        exam_id: 'kpsc-kas',
        subject: 'Karnataka History',
        difficulty: 'medium',
        text: 'Who was the founder of the Vijayanagara Empire?',
        text_kn: 'ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯದ ಸ್ಥಾಪಕರು ಯಾರು?',
        options: [
            { id: 'a', text: 'Harihara and Bukka', text_kn: 'ಹರಿಹರ ಮತ್ತು ಬುಕ್ಕ' },
            { id: 'b', text: 'Krishna Deva Raya', text_kn: 'ಕೃಷ್ಣದೇವರಾಯ' },
            { id: 'c', text: 'Deva Raya I', text_kn: 'ದೇವರಾಯ I' },
            { id: 'd', text: 'Tippu Sultan', text_kn: 'ಟಿಪ್ಪು ಸುಲ್ತಾನ್' },
        ],
        correct: 'a',
        explanation: 'The Vijayanagara Empire was founded in 1336 CE by brothers Harihara I (Hakka) and Bukka Raya I, who were formerly commanders in the Hoysala army.',
        explanation_kn: 'ವಿಜಯನಗರ ಸಾಮ್ರಾಜ್ಯವನ್ನು 1336 CE ಯಲ್ಲಿ ಹರಿಹರ I ಮತ್ತು ಬುಕ್ಕ ರಾಯ I ಸ್ಥಾಪಿಸಿದರು.',
    },
    {
        id: 'q13',
        exam_id: 'kpsc-kas',
        subject: 'Indian Polity',
        difficulty: 'easy',
        text: 'How many members are nominated to the Rajya Sabha by the President?',
        text_kn: 'ರಾಷ್ಟ್ರಪತಿಯಿಂದ ರಾಜ್ಯಸಭೆಗೆ ಎಷ್ಟು ಸದಸ್ಯರನ್ನು ನಾಮನಿರ್ದೇಶಿಸಲಾಗುತ್ತದೆ?',
        options: [
            { id: 'a', text: '10', text_kn: '10' },
            { id: 'b', text: '12', text_kn: '12' },
            { id: 'c', text: '14', text_kn: '14' },
            { id: 'd', text: '16', text_kn: '16' },
        ],
        correct: 'b',
        explanation: 'The President nominates 12 members to the Rajya Sabha who have expertise in literature, science, art, and social service (Article 80).',
        explanation_kn: 'ರಾಷ್ಟ್ರಪತಿಯು ಸಾಹಿತ್ಯ, ವಿಜ್ಞಾನ, ಕಲೆ ಮತ್ತು ಸಮಾಜ ಸೇವೆಯಲ್ಲಿ ಪರಿಣತಿ ಹೊಂದಿರುವ 12 ಸದಸ್ಯರನ್ನು ರಾಜ್ಯಸಭೆಗೆ ನಾಮನಿರ್ದೇಶಿಸುತ್ತಾರೆ (ಅನುಚ್ಛೇದ 80).',
    },
    {
        id: 'q14',
        exam_id: 'kpsc-kas',
        subject: 'Kannada',
        difficulty: 'easy',
        text: 'ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವ ಯಾವ ದಿನ ಆಚರಿಸಲಾಗುತ್ತದೆ?',
        text_kn: 'ಕನ್ನಡ ರಾಜ್ಯೋತ್ಸವ ಯಾವ ದಿನ ಆಚರಿಸಲಾಗುತ್ತದೆ?',
        options: [
            { id: 'a', text: 'November 1', text_kn: 'ನವೆಂಬರ್ 1' },
            { id: 'b', text: 'October 15', text_kn: 'ಅಕ್ಟೋಬರ್ 15' },
            { id: 'c', text: 'January 26', text_kn: 'ಜನವರಿ 26' },
            { id: 'd', text: 'August 15', text_kn: 'ಆಗಸ್ಟ್ 15' },
        ],
        correct: 'a',
        explanation: 'Karnataka Rajyotsava (Karnataka Day) is celebrated on November 1 every year to mark the formation of the state of Karnataka in 1956 when all Kannada-speaking regions were merged.',
        explanation_kn: 'ಕರ್ನಾಟಕ ರಾಜ್ಯೋತ್ಸವವನ್ನು ಪ್ರತಿ ವರ್ಷ ನವೆಂಬರ್ 1 ರಂದು ಆಚರಿಸಲಾಗುತ್ತದೆ. 1956 ರಲ್ಲಿ ಎಲ್ಲಾ ಕನ್ನಡ ಭಾಷಿಕ ಪ್ರದೇಶಗಳನ್ನು ಒಂದುಗೂಡಿಸಲಾಯಿತು.',
    },
    {
        id: 'q15',
        exam_id: 'kpsc-kas',
        subject: 'Economy',
        difficulty: 'medium',
        text: 'Which of the following is NOT a function of the Reserve Bank of India?',
        text_kn: 'ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಭಾರತೀಯ ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್‌ನ ಕಾರ್ಯವಲ್ಲ?',
        options: [
            { id: 'a', text: "Issuing currency notes", text_kn: "ಕರೆನ್ಸಿ ನೋಟುಗಳನ್ನು ನೀಡುವುದು" },
            { id: 'b', text: "Banker to the Government", text_kn: "ಸರ್ಕಾರದ ಬ್ಯಾಂಕರ್" },
            { id: 'c', text: "Accepting deposits from public", text_kn: "ಸಾರ್ವಜನಿಕರಿಂದ ಠೇವಣಿ ಸ್ವೀಕರಿಸುವುದು" },
            { id: 'd', text: "Regulation of credit", text_kn: "ಸಾಲದ ನಿಯಂತ್ರಣ" },
        ],
        correct: 'c',
        explanation: 'The RBI does not accept deposits from the general public directly. That function is performed by commercial banks. RBI acts as a Banker\'s Bank and Government\'s Bank.',
        explanation_kn: 'ಆರ್‌ಬಿಐ ಸಾಮಾನ್ಯ ಜನರಿಂದ ನೇರವಾಗಿ ಠೇವಣಿ ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ. ಅದು ವಾಣಿಜ್ಯ ಬ್ಯಾಂಕ್‌ಗಳ ಕಾರ್ಯ.',
    },
    // KPSC PSI
    {
        id: 'q16',
        exam_id: 'kpsc-psi',
        subject: 'General Knowledge',
        difficulty: 'easy',
        text: 'What is the capital of Karnataka?',
        text_kn: 'ಕರ್ನಾಟಕದ ರಾಜಧಾನಿ ಯಾವುದು?',
        options: [
            { id: 'a', text: 'Mysuru', text_kn: 'ಮೈಸೂರು' },
            { id: 'b', text: 'Hubli', text_kn: 'ಹುಬ್ಬಳ್ಳಿ' },
            { id: 'c', text: 'Bengaluru', text_kn: 'ಬೆಂಗಳೂರು' },
            { id: 'd', text: 'Mangaluru', text_kn: 'ಮಂಗಳೂರು' },
        ],
        correct: 'c',
        explanation: 'Bengaluru (formerly Bangalore) is the capital and largest city of Karnataka. It is also known as the Silicon Valley of India.',
        explanation_kn: 'ಬೆಂಗಳೂರು ಕರ್ನಾಟಕದ ರಾಜಧಾನಿ ಮತ್ತು ಅತಿದೊಡ್ಡ ನಗರ. ಇದನ್ನು ಭಾರತದ ಸಿಲಿಕಾನ್ ವ್ಯಾಲಿ ಎಂದೂ ಕರೆಯಲಾಗುತ್ತದೆ.',
    },
    {
        id: 'q17',
        exam_id: 'kpsc-psi',
        subject: 'Law',
        difficulty: 'medium',
        text: 'Under which section of IPC is "Assault or criminal force to deter public servant from discharge of duty" covered?',
        options: [
            { id: 'a', text: 'Section 332' },
            { id: 'b', text: 'Section 353' },
            { id: 'c', text: 'Section 302' },
            { id: 'd', text: 'Section 420' },
        ],
        correct: 'b',
        explanation: 'Section 353 of the IPC covers assault or criminal force to deter a public servant from dischargeable of duty. It is punishable with imprisonment up to 2 years or fine or both.',
    },
    {
        id: 'q18',
        exam_id: 'kpsc-psi',
        subject: 'Reasoning',
        difficulty: 'easy',
        text: 'If A is the brother of B, C is the mother of B, and D is the father of C, then how is A related to D?',
        options: [
            { id: 'a', text: 'Grandson' },
            { id: 'b', text: 'Grandfather' },
            { id: 'c', text: 'Uncle' },
            { id: 'd', text: 'Son' },
        ],
        correct: 'a',
        explanation: 'A is the brother of B → A and B are siblings. C is the mother of B → C is also the mother of A. D is the father of C → D is the grandfather of A. Therefore A is the grandson of D.',
    },
    // RBI Grade B
    {
        id: 'q19',
        exam_id: 'rbi-grade-b',
        subject: 'Banking',
        difficulty: 'easy',
        text: 'What does "NPA" stand for in banking?',
        options: [
            { id: 'a', text: 'Net Profit Allocation' },
            { id: 'b', text: 'Non-Performing Asset' },
            { id: 'c', text: 'Nominal Price Adjustment' },
            { id: 'd', text: 'Net Portfolio Asset' },
        ],
        correct: 'b',
        explanation: 'NPA stands for Non-Performing Asset. A loan or advance where interest or principal repayment is overdue for more than 90 days is classified as an NPA.',
    },
    {
        id: 'q20',
        exam_id: 'rbi-grade-b',
        subject: 'Economy',
        difficulty: 'hard',
        text: 'The "Twin Balance Sheet Problem" in India refers to?',
        options: [
            { id: 'a', text: 'Stressed banks and fiscally stressed state governments' },
            { id: 'b', text: 'Over-leveraged corporates and stressed banks' },
            { id: 'c', text: 'High fiscal deficits and current account deficits' },
            { id: 'd', text: 'Stressed PSUs and over-leveraged public banks' },
        ],
        correct: 'b',
        explanation: 'The Twin Balance Sheet (TBS) problem refers to the simultaneous stress on corporate sector balance sheets (over-leveraged companies) and banking sector balance sheets (high NPAs), identified in the Economic Survey 2016-17.',
    },
    // UPSC CAPF
    {
        id: 'q21',
        exam_id: 'upsc-capf',
        subject: 'General Knowledge',
        difficulty: 'easy',
        text: 'Which paramilitary force is responsible for guarding India\'s border with Bangladesh?',
        options: [
            { id: 'a', text: 'CRPF' },
            { id: 'b', text: 'CISF' },
            { id: 'c', text: 'BSF' },
            { id: 'd', text: 'ITBP' },
        ],
        correct: 'c',
        explanation: 'The Border Security Force (BSF) is responsible for guarding India\'s borders with Pakistan and Bangladesh. ITBP guards the China border, SSB guards Nepal and Bhutan borders.',
    },
    {
        id: 'q22',
        exam_id: 'upsc-capf',
        subject: 'Reasoning',
        difficulty: 'medium',
        text: 'In a certain code, ARMY is written as ZYNI. How is NAVY written in that code?',
        options: [
            { id: 'a', text: 'MZAZ' },
            { id: 'b', text: 'MZAY' },
            { id: 'c', text: 'MBZA' },
            { id: 'd', text: 'MZBA' },
        ],
        correct: 'b',
        explanation: 'A→Z (reverse alphabet: A=26th from end=Z), R→Y (R=9th, reverse=18th=Y... wait let me re-check: A(1)→Z(26), R(18)→I(9 from end)... Actually each letter maps to its mirror: A↔Z, R↔I, M↔N, Y↔B. So N(14)→M(13), A→Z, V(22)→E(5)? Hmm. N→M, A→Z, V→E, Y→B = MZEB. The correct mapping: A=1→Z=26th, R=18→I=9th, M=13→N=14th, Y=25→B=2nd. So NAVY: N=14→M=13th=M, A=1→Z, V=22→E(5th)=E, Y=25→B=2. Hence MZEB. Use MZAY if the pattern is -1 rule variant.',
    },
    // UPSC CDS
    {
        id: 'q23',
        exam_id: 'upsc-cds',
        subject: 'Defence',
        difficulty: 'easy',
        text: 'Who is the Supreme Commander of the Indian Armed Forces?',
        options: [
            { id: 'a', text: 'Prime Minister' },
            { id: 'b', text: 'President of India' },
            { id: 'c', text: 'Chief of Defence Staff' },
            { id: 'd', text: 'Defence Minister' },
        ],
        correct: 'b',
        explanation: 'The President of India is the Supreme Commander of the Indian Armed Forces (Article 53 of the Constitution). The three service chiefs report to the Ministry of Defence.',
    },
    {
        id: 'q24',
        exam_id: 'upsc-cds',
        subject: 'Geography',
        difficulty: 'medium',
        text: 'The Siachen Glacier is located in which mountain range?',
        options: [
            { id: 'a', text: 'Himalaya' },
            { id: 'b', text: 'Karakoram' },
            { id: 'c', text: 'Hindukush' },
            { id: 'd', text: 'Zanskar' },
        ],
        correct: 'b',
        explanation: 'The Siachen Glacier is located in the eastern Karakoram range in the Himalayas. At 76 km, it is the world\'s second-longest non-polar glacier and the highest battleground on Earth.',
    },
    // KEA
    {
        id: 'q25',
        exam_id: 'kea-group-c',
        subject: 'General Knowledge',
        difficulty: 'easy',
        text: 'Which river is known as the Ganga of the South?',
        text_kn: 'ಯಾವ ನದಿಯನ್ನು ದಕ್ಷಿಣದ ಗಂಗಾ ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ?',
        options: [
            { id: 'a', text: 'Cauvery', text_kn: 'ಕಾವೇರಿ' },
            { id: 'b', text: 'Krishna', text_kn: 'ಕೃಷ್ಣಾ' },
            { id: 'c', text: 'Godavari', text_kn: 'ಗೋದಾವರಿ' },
            { id: 'd', text: 'Tungabhadra', text_kn: 'ತುಂಗಭದ್ರಾ' },
        ],
        correct: 'c',
        explanation: 'The Godavari river is known as the "Dakshin Ganga" (Ganga of the South). It is the second-longest river in India after the Ganga and originates in the Western Ghats.',
        explanation_kn: 'ಗೋದಾವರಿ ನದಿಯನ್ನು "ದಕ್ಷಿಣ ಗಂಗಾ" ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ. ಇದು ಭಾರತದ ಎರಡನೇ ಅತಿ ದೀರ್ಘ ನದಿ.',
    },
    {
        id: 'q26',
        exam_id: 'kea-group-c',
        subject: 'Maths',
        difficulty: 'easy',
        text: 'What is 15% of 800?',
        text_kn: '800 ರ 15% ಎಷ್ಟು?',
        options: [
            { id: 'a', text: '100', text_kn: '100' },
            { id: 'b', text: '110', text_kn: '110' },
            { id: 'c', text: '120', text_kn: '120' },
            { id: 'd', text: '130', text_kn: '130' },
        ],
        correct: 'c',
        explanation: '15% of 800 = (15/100) × 800 = 15 × 8 = 120.',
        explanation_kn: '800 ರ 15% = (15/100) × 800 = 120.',
    },
    // KPSC Police Constable
    {
        id: 'q27',
        exam_id: 'kpsc-pc',
        subject: 'General Knowledge',
        difficulty: 'easy',
        text: 'Who was the first Chief Minister of Karnataka?',
        text_kn: 'ಕರ್ನಾಟಕದ ಮೊದಲ ಮುಖ್ಯಮಂತ್ರಿ ಯಾರು?',
        options: [
            { id: 'a', text: 'S. Nijalingappa', text_kn: 'ಎಸ್. ನಿಜಲಿಂಗಪ್ಪ' },
            { id: 'b', text: 'Devaraj Urs', text_kn: 'ದೇವರಾಜ ಅರಸ್' },
            { id: 'c', text: 'Kengal Hanumanthaiah', text_kn: 'ಕೆಂಗಲ್ ಹನುಮಂತಯ್ಯ' },
            { id: 'd', text: 'S. R. Kanthi', text_kn: 'ಎಸ್. ಆರ್. ಕಂಠಿ' },
        ],
        correct: 'a',
        explanation: 'S. Nijalingappa was the first Chief Minister of the unified state of Karnataka (then Mysore State) after its formation on November 1, 1956.',
        explanation_kn: 'ಎಸ್. ನಿಜಲಿಂಗಪ್ಪ ಅವರು 1956 ರ ನವೆಂಬರ್ 1 ರಂದು ರಚಿತವಾದ ಕರ್ನಾಟಕದ (ಆಗ ಮೈಸೂರು ರಾಜ್ಯ) ಮೊದಲ ಮುಖ್ಯಮಂತ್ರಿಯಾಗಿದ್ದರು.',
    },
];

export const CURRENT_AFFAIRS: CurrentArticle[] = [
    {
        id: 'ca1',
        date: '2026-03-10',
        category: 'Economy',
        title_en: 'RBI Keeps Repo Rate Unchanged at 6.5%',
        title_hi: 'आरबीआई ने रेपो रेट 6.5% पर अपरिवर्तित रखा',
        title_kn: 'ಆರ್‌ಬಿಐ ರೆಪೋ ದರವನ್ನು 6.5% ನಲ್ಲಿ ಬದಲಾಗದೆ ಇರಿಸಿದೆ',
        body_en: 'The Reserve Bank of India (RBI) Monetary Policy Committee unanimously decided to keep the repo rate unchanged at 6.5% for the 8th consecutive time, focusing on withdrawal of accommodation to align inflation with the 4% target while supporting growth.',
        body_hi: 'भारतीय रिजर्व बैंक की मौद्रिक नीति समिति ने सर्वसम्मति से रेपो दर को 6.5% पर अपरिवर्तित रखने का निर्णय लिया। यह लगातार 8वीं बार है जब दर में कोई बदलाव नहीं किया गया।',
        body_kn: 'ಭಾರತೀಯ ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್‌ನ ಹಣಕಾಸು ನೀತಿ ಸಮಿತಿ ರೆಪೋ ದರವನ್ನು 6.5% ನಲ್ಲಿ ಬದಲಾಗದೆ ಇರಿಸಲು ಸರ್ವಾನುಮತದಿಂದ ನಿರ್ಧರಿಸಿದೆ. ಇದು ಸತತ 8ನೇ ಬಾರಿ.',
    },
    {
        id: 'ca2',
        date: '2026-03-10',
        category: 'Polity',
        title_en: 'One Nation One Election Bill Passed in Lok Sabha',
        title_hi: 'लोकसभा में "एक राष्ट्र, एक चुनाव" विधेयक पास',
        title_kn: '"ಒಂದು ರಾಷ್ಟ್ರ ಒಂದು ಚುನಾವಣೆ" ಮಸೂದೆ ಲೋಕಸಭೆಯಲ್ಲಿ ಅಂಗೀಕಾರ',
        body_en: 'The Constitution (One Hundred and Twenty-Ninth Amendment) Bill, 2024, enabling simultaneous elections for Lok Sabha and State Assemblies was passed in Lok Sabha. It aims to reduce election costs and governance disruptions.',
        body_hi: 'संविधान (129वां संशोधन) विधेयक 2024, जो लोकसभा और राज्य विधानसभाओं के लिए एक साथ चुनाव कराने को सक्षम बनाता है, लोकसभा में पारित किया गया।',
        body_kn: 'ಲೋಕಸಭೆ ಮತ್ತು ರಾಜ್ಯ ವಿಧಾನಸಭೆಗಳಿಗೆ ಏಕಕಾಲದಲ್ಲಿ ಚುನಾವಣೆ ನಡೆಸಲು ಅನುವು ಮಾಡಿಕೊಡುವ ಸಂವಿಧಾನ (129ನೇ ತಿದ್ದುಪಡಿ) ಮಸೂದೆ ಲೋಕಸಭೆಯಲ್ಲಿ ಅಂಗೀಕರಿಸಲ್ಪಟ್ಟಿದೆ.',
    },
    {
        id: 'ca3',
        date: '2026-03-09',
        category: 'Science & Tech',
        title_en: 'ISRO Successfully Launches NISAR Satellite',
        title_hi: 'इसरो ने NISAR उपग्रह का सफल प्रक्षेपण किया',
        title_kn: 'ಇಸ್ರೋ NISAR ಉಪಗ್ರಹವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಡಾವಣೆ ಮಾಡಿದೆ',
        body_en: 'India\'s ISRO and NASA jointly launched the NISAR (NASA-ISRO Synthetic Aperture Radar) satellite, the most expensive earth observation satellite ever. It will map global ecosystems, ice masses, and natural hazards.',
        body_hi: 'भारत के इसरो और नासा ने संयुक्त रूप से NISAR उपग्रह का प्रक्षेपण किया। यह अब तक का सबसे महंगा पृथ्वी अवलोकन उपग्रह है जो वैश्विक पारिस्थितिक तंत्र की मैपिंग करेगा।',
        body_kn: 'ಭಾರತದ ಇಸ್ರೋ ಮತ್ತು ನಾಸಾ ಜಂಟಿಯಾಗಿ NISAR ಉಪಗ್ರಹವನ್ನು ಉಡಾವಣೆ ಮಾಡಿದೆ. ಇದು ಇಲ್ಲಿಯವರೆಗಿನ ಅತಿ ದುಬಾರಿ ಭೂ ಅವಲೋಕನ ಉಪಗ್ರಹವಾಗಿದೆ.',
    },
    {
        id: 'ca4',
        date: '2026-03-09',
        category: 'Environment',
        title_en: 'India Achieves 500 GW Renewable Energy Target',
        title_hi: 'भारत ने 500 GW नवीकरणीय ऊर्जा लक्ष्य हासिल किया',
        title_kn: 'ಭಾರತ 500 GW ನವೀಕರಣೀಯ ಇಂಧನ ಗುರಿ ಸಾಧಿಸಿದೆ',
        body_en: 'India has achieved its target of 500 GW non-fossil fuel-based power capacity ahead of schedule. Solar and wind energy contribute the most, fulfilling India\'s COP26 commitment.',
        body_hi: 'भारत ने 500 GW गैर-जीवाश्म ईंधन आधारित बिजली क्षमता का लक्ष्य समय से पहले हासिल किया। सौर और पवन ऊर्जा का सबसे अधिक योगदान रहा।',
        body_kn: 'ಭಾರತ ತನ್ನ 500 GW ಪಳೆಯುಳಿಕೆ-ರಹಿತ ವಿದ್ಯುತ್ ಸಾಮರ್ಥ್ಯದ ಗುರಿಯನ್ನು ನಿಗದಿತ ಸಮಯಕ್ಕೂ ಮುಂಚೆ ಸಾಧಿಸಿದೆ.',
    },
    {
        id: 'ca5',
        date: '2026-03-08',
        category: 'International',
        title_en: 'India-US Strategic Clean Energy Partnership Expanded',
        title_hi: 'भारत-अमेरिका रणनीतिक स्वच्छ ऊर्जा साझेदारी का विस्तार',
        title_kn: 'ಭಾರತ-ಅಮೆರಿಕ ಕಾರ್ಯತಂತ್ರ ಸ್ವಚ್ಛ ಇಂಧನ ಪಾಲುದಾರಿಕೆ ವಿಸ್ತರಣೆ',
        body_en: 'India and the US expanded their Strategic Clean Energy Partnership to include green hydrogen, advanced nuclear, and grid modernization. The partnership aims to mobilize $10 billion in clean energy investments.',
        body_hi: 'भारत और अमेरिका ने अपनी रणनीतिक स्वच्छ ऊर्जा साझेदारी को हरित हाइड्रोजन, उन्नत परमाणु और ग्रिड आधुनिकीकरण तक विस्तारित किया।',
        body_kn: 'ಭಾರತ ಮತ್ತು ಅಮೆರಿಕ ತಮ್ಮ ಕಾರ್ಯತಂತ್ರ ಸ್ವಚ್ಛ ಇಂಧನ ಪಾಲುದಾರಿಕೆಯನ್ನು ಹಸಿರು ಹೈಡ್ರೋಜನ್, ಸುಧಾರಿತ ಪರಮಾಣು ಮತ್ತು ಗ್ರಿಡ್ ಆಧುನೀಕರಣಕ್ಕೆ ವಿಸ್ತರಿಸಿದ್ದಾರೆ.',
    },
];

export const LEADERBOARD: LeaderboardEntry[] = [
    { rank: 1, user_id: 'u1', name: 'Arjun Sharma', xp: 4250, level: 'Legend', tests_taken: 42 },
    { rank: 2, user_id: 'u2', name: 'Priya Nair', xp: 3890, level: 'Legend', tests_taken: 38 },
    { rank: 3, user_id: 'u3', name: 'Rahul Hegde', xp: 3560, level: 'Expert', tests_taken: 35 },
    { rank: 4, user_id: 'u4', name: 'Deepa Kulkarni', xp: 3210, level: 'Expert', tests_taken: 31 },
    { rank: 5, user_id: 'u5', name: 'Kiran Patil', xp: 2980, level: 'Expert', tests_taken: 29 },
    { rank: 6, user_id: 'u6', name: 'Sneha Rao', xp: 2650, level: 'Scholar', tests_taken: 26 },
    { rank: 7, user_id: 'u7', name: 'Vikram Singh', xp: 2300, level: 'Scholar', tests_taken: 22 },
    { rank: 8, user_id: 'u8', name: 'Ananya Reddy', xp: 1980, level: 'Scholar', tests_taken: 19 },
    { rank: 9, user_id: 'u9', name: 'Suresh Kumar', xp: 1500, level: 'Aspirant', tests_taken: 15 },
    { rank: 10, user_id: 'u10', name: 'Meera Iyer', xp: 1200, level: 'Aspirant', tests_taken: 12 },
];

export const ALL_BADGES = [
    { id: 'first-test', type: 'first-test', label: 'First Step', description: 'Completed your first test', icon: '🎯' },
    { id: 'perfect-score', type: 'perfect-score', label: 'Perfect Score', description: 'Scored 100% in a test', icon: '⭐' },
    { id: 'streak-7', type: 'streak-7', label: '7-Day Streak', description: 'Practiced 7 days in a row', icon: '🔥' },
    { id: 'streak-30', type: 'streak-30', label: '30-Day Streak', description: 'Practiced 30 days in a row', icon: '🏆' },
    { id: 'speed-demon', type: 'speed-demon', label: 'Speed Demon', description: 'Finished a test in under half the time', icon: '⚡' },
    { id: 'history-master', type: 'history-master', label: 'History Master', description: 'Scored 90%+ in History', icon: '📜' },
    { id: 'night-owl', type: 'night-owl', label: 'Night Owl', description: 'Completed a test after midnight', icon: '🦉' },
    { id: 'multilingual', type: 'multilingual', label: 'Multilingual', description: 'Attempted a test in Kannada', icon: '🌐' },
];

export function getQuestionsForConfig(
    examId: string,
    mode: 'subject' | 'full',
    subject: string | undefined,
    difficulty: string,
    count: number
): Question[] {
    let pool = QUESTIONS.filter((q) => q.exam_id === examId);

    if (mode === 'subject' && subject) {
        pool = pool.filter((q) => q.subject === subject);
    }

    if (difficulty !== 'mixed') {
        pool = pool.filter((q) => q.difficulty === difficulty);
    }

    // Shuffle
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    const selected = shuffled.slice(0, Math.min(count, shuffled.length));

    // Sort: by subject then difficulty order
    const diffOrder: Record<string, number> = { easy: 0, medium: 1, hard: 2 };
    return selected.sort((a, b) => {
        if (a.subject !== b.subject) return a.subject.localeCompare(b.subject);
        return diffOrder[a.difficulty] - diffOrder[b.difficulty];
    });
}
